# Generated by Django 2.1.5 on 2019-02-21 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0004_projectbudget'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectBids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='bidding',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
