# Generated by Django 2.1.5 on 2019-02-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0005_auto_20190221_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='bidding',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
