# Generated by Django 2.1.5 on 2019-02-21 13:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('engineering', '0006_auto_20190221_1300'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectbids',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='projectbids',
            name='bid_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectbids',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 2, 21, 13, 24, 14, 512148, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectbids',
            name='project',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='engineering.Project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectbids',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectbids',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='projectbids',
            name='vendor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
