# Generated by Django 2.1.5 on 2019-02-21 13:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('engineering', '0007_auto_20190221_1324'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectBids',
            new_name='ProjectBid',
        ),
    ]
