# Generated by Django 2.1.5 on 2019-02-23 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0008_auto_20190221_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectbid',
            name='bid_status',
            field=models.CharField(choices=[('Open', 'Open'), ('Accepted', 'Accepted'), ('Denied', 'Denied')], default='Open', max_length=68),
        ),
    ]
