# Generated by Django 2.1.5 on 2019-02-24 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0010_projectquote_projectquoteitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectquote',
            name='vendor',
        ),
    ]
