# Generated by Django 2.1.5 on 2019-03-20 19:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('engineering', '0012_projectbid_rfq'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='project_member', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectquoteitem',
            name='quote_price',
            field=models.FloatField(default=0),
        ),
    ]
