# Generated by Django 2.1.5 on 2019-03-22 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0015_projectfabrication'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectfabrication',
            old_name='bid_status',
            new_name='fabrication_status',
        ),
    ]
