# Generated by Django 2.1.5 on 2019-04-03 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0018_projectstage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectstage',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engineering.Project'),
        ),
    ]
