# Generated by Django 2.1.5 on 2019-04-29 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0020_project_commissioned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='owner_email',
            field=models.EmailField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='owner_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
