# Generated by Django 2.1.5 on 2019-04-29 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0021_auto_20190429_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectfile',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
