# Generated by Django 2.1.5 on 2019-05-01 11:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0023_auto_20190429_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfabrication',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2019, 5, 1, 11, 45, 48, 863782, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
