# Generated by Django 2.1.5 on 2019-04-03 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0003_commission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commission',
            old_name='commission_by',
            new_name='commissioned_by',
        ),
    ]
