# Generated by Django 2.1.5 on 2019-05-05 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0025_historicalproject'),
        ('warehouse', '0004_stockrelease_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='warehouse',
        ),
        migrations.RemoveField(
            model_name='stockrelease',
            name='warehouse',
        ),
        migrations.AddField(
            model_name='stock',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='engineering.Project'),
            preserve_default=False,
        ),
    ]
