# Generated by Django 2.1.5 on 2019-03-23 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0003_surveyquestion_surveyquestionanswers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SurveyQuestionAnswers',
            new_name='SurveyQuestionAnswer',
        ),
    ]
