# Generated by Django 2.1.5 on 2019-03-23 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0005_surveyquestion_survey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyquestion',
            name='question_type',
            field=models.CharField(choices=[('1', 'Yes/No'), ('2', 'Numerical'), ('3', 'Open Ended')], default='1', max_length=68),
        ),
    ]
