# Generated by Django 2.1.5 on 2019-04-03 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0006_auto_20190323_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='survey_type',
            field=models.CharField(default='Shipping', max_length=68),
        ),
    ]
