# Generated by Django 2.1.5 on 2019-04-04 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0008_surveyquestionanswer_answered_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyquestionanswer',
            name='answered_by',
        ),
    ]
