# Generated by Django 2.1.5 on 2019-05-01 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0012_auto_20190405_0409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='survey_type',
            field=models.CharField(choices=[('Shipping', 'Shipping'), ('Fabrication', 'Fabrication')], default='Shipping', max_length=68),
        ),
    ]
