# Generated by Django 2.1.5 on 2019-05-02 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0013_auto_20190501_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='survey_type',
            field=models.CharField(choices=[('Shipping', 'Shipping'), ('Fabrication', 'Fabrication'), ('Construction', 'Construction')], default='Shipping', max_length=68),
        ),
    ]
