# Generated by Django 2.1.5 on 2019-05-03 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0025_historicalproject'),
        ('compliance', '0014_auto_20190502_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyquestionanswer',
            name='task_given',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='engineering.ProjectFabrication'),
            preserve_default=False,
        ),
    ]
